### ISSUE TITLE
Set default branch to main

### ISSUE THREAD

**Issue by OR13** [BlockchainCommons/did-method-onion#1]
I don't have permissions to do so.

**Comment by ChristopherA** [comment]
I've changed to access from `write` to `maintain`.

**Comment by OR13** [comment]
Apparently I still can't change the default branch from https://github.com/BlockchainCommons/did-method-onion/tree/feat/initial-commit to `main`... which is sorta silly since I pushed the first branch in the first place.

**Comment by ChristopherA** [comment]
I just changed you from `maintain` to `admin` — you should now be able to do everything ;-)

**Comment by OR13** [comment]
i can :)
