### ISSUE TITLE
Use tor keypair directly?

### ISSUE THREAD

**Issue by jernst** [BlockchainCommons/did-method-onion#12]
The public key of the onion service is its address. Is it possible to use that key pair for the verification as well, instead of generating a second one? That would be self-authenticating ...

**Comment by gorazdko** [comment]
Yes, you can find the algo to convert an onion address into pubkey in #10

You can also take a look at the example which uses an 'onion address' (so to speak) for verification:

* http://fscst5exmlmr262byztwz4kzhggjlzumvc2ndvgytzoucr2tkgxf7mid.onion/vc_sw2.json
* http://fscst5exmlmr262byztwz4kzhggjlzumvc2ndvgytzoucr2tkgxf7mid.onion/.well-known/did.json

You can verify the example with didkit, see https://github.com/spruceid/didkit/pull/125

Lmk if this answers your question.

**Comment by ChristopherA** [comment]
@jernst @gorazdko Is this issue closed?

**Comment by gorazdko** [comment]
Yes, you can close this.
